//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NieGadalismyOGrach.Properties {
    using System;
    
    
    /// <summary>
    ///   Klasa zasobu wymagająca zdefiniowania typu do wyszukiwania zlokalizowanych ciągów itd.
    /// </summary>
    // Ta klasa została automatycznie wygenerowana za pomocą klasy StronglyTypedResourceBuilder
    // przez narzędzie, takie jak ResGen lub Visual Studio.
    // Aby dodać lub usunąć składową, edytuj plik ResX, a następnie ponownie uruchom narzędzie ResGen
    // z opcją /str lub ponownie utwórz projekt VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        /// Zwraca buforowane wystąpienie ResourceManager używane przez tę klasę.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NieGadalismyOGrach.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Przesłania właściwość CurrentUICulture bieżącego wątku dla wszystkich
        ///   przypadków przeszukiwania zasobów za pomocą tej klasy zasobów wymagającej zdefiniowania typu.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Amaranth Pink.
        /// </summary>
        public static string AmaranthPink {
            get {
                return ResourceManager.GetString("AmaranthPink", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Baby Pink.
        /// </summary>
        public static string BabyPink {
            get {
                return ResourceManager.GetString("BabyPink", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Baker-Miller Pink.
        /// </summary>
        public static string BakerMillerPink {
            get {
                return ResourceManager.GetString("BakerMillerPink", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Barbie Pink.
        /// </summary>
        public static string BarbiePink {
            get {
                return ResourceManager.GetString("BarbiePink", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Black.
        /// </summary>
        public static string Black {
            get {
                return ResourceManager.GetString("Black", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Blue.
        /// </summary>
        public static string Blue {
            get {
                return ResourceManager.GetString("Blue", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Bright Pink.
        /// </summary>
        public static string BrightPink {
            get {
                return ResourceManager.GetString("BrightPink", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Brink Pink.
        /// </summary>
        public static string BrinkPink {
            get {
                return ResourceManager.GetString("BrinkPink", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Brown.
        /// </summary>
        public static string Brown {
            get {
                return ResourceManager.GetString("Brown", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Cameo Pink.
        /// </summary>
        public static string CameoPink {
            get {
                return ResourceManager.GetString("CameoPink", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Carnation Pink.
        /// </summary>
        public static string CarnationPink {
            get {
                return ResourceManager.GetString("CarnationPink", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Champagne Pink.
        /// </summary>
        public static string ChampagnePink {
            get {
                return ResourceManager.GetString("ChampagnePink", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Charm Pink.
        /// </summary>
        public static string CharmPink {
            get {
                return ResourceManager.GetString("CharmPink", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Check.
        /// </summary>
        public static string Check {
            get {
                return ResourceManager.GetString("Check", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Cherry Blossom Pink.
        /// </summary>
        public static string CherryBlossomPink {
            get {
                return ResourceManager.GetString("CherryBlossomPink", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Chilean Pink.
        /// </summary>
        public static string ChileanPink {
            get {
                return ResourceManager.GetString("ChileanPink", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu China Pink.
        /// </summary>
        public static string ChinaPink {
            get {
                return ResourceManager.GetString("ChinaPink", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Click the button..
        /// </summary>
        public static string Click_The_Button {
            get {
                return ResourceManager.GetString("Click_The_Button", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Click the button on the left.
        /// </summary>
        public static string ClickButtonLeft {
            get {
                return ResourceManager.GetString("ClickButtonLeft", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Click the button on the right.
        /// </summary>
        public static string ClickButtonRight {
            get {
                return ResourceManager.GetString("ClickButtonRight", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Congratulations..
        /// </summary>
        public static string Congratz {
            get {
                return ResourceManager.GetString("Congratz", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Coral Pink.
        /// </summary>
        public static string CoralPink {
            get {
                return ResourceManager.GetString("CoralPink", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Cotton Candy.
        /// </summary>
        public static string CottonCandy {
            get {
                return ResourceManager.GetString("CottonCandy", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Click until value is 0.
        /// </summary>
        public static string Count_To_0 {
            get {
                return ResourceManager.GetString("Count_To_0", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Cyan.
        /// </summary>
        public static string Cyan {
            get {
                return ResourceManager.GetString("Cyan", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Deep Pink.
        /// </summary>
        public static string DeepPink {
            get {
                return ResourceManager.GetString("DeepPink", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Fairy Tale.
        /// </summary>
        public static string FairyTale {
            get {
                return ResourceManager.GetString("FairyTale", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Fandango Pink.
        /// </summary>
        public static string FandangoPink {
            get {
                return ResourceManager.GetString("FandangoPink", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu French Pink.
        /// </summary>
        public static string FrenchPink {
            get {
                return ResourceManager.GetString("FrenchPink", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Gold.
        /// </summary>
        public static string Gold {
            get {
                return ResourceManager.GetString("Gold", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Gray.
        /// </summary>
        public static string Gray {
            get {
                return ResourceManager.GetString("Gray", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Green.
        /// </summary>
        public static string Green {
            get {
                return ResourceManager.GetString("Green", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Hot Pink.
        /// </summary>
        public static string HotPink {
            get {
                return ResourceManager.GetString("HotPink", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Lavender Pink.
        /// </summary>
        public static string LavenderPink {
            get {
                return ResourceManager.GetString("LavenderPink", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Light Deep Pink.
        /// </summary>
        public static string LightDeepPink {
            get {
                return ResourceManager.GetString("LightDeepPink", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Light Hot Pink.
        /// </summary>
        public static string LightHotPink {
            get {
                return ResourceManager.GetString("LightHotPink", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Light Pink.
        /// </summary>
        public static string LightPink {
            get {
                return ResourceManager.GetString("LightPink", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Lime.
        /// </summary>
        public static string Lime {
            get {
                return ResourceManager.GetString("Lime", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Mexican Pink.
        /// </summary>
        public static string MexicanPink {
            get {
                return ResourceManager.GetString("MexicanPink", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Mimi Pink.
        /// </summary>
        public static string MimiPink {
            get {
                return ResourceManager.GetString("MimiPink", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Mountbatten Pink.
        /// </summary>
        public static string MountbattenPink {
            get {
                return ResourceManager.GetString("MountbattenPink", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Navy.
        /// </summary>
        public static string Navy {
            get {
                return ResourceManager.GetString("Navy", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu New York Pink.
        /// </summary>
        public static string NewYorkPink {
            get {
                return ResourceManager.GetString("NewYorkPink", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Orange.
        /// </summary>
        public static string Orange {
            get {
                return ResourceManager.GetString("Orange", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Orchid Pink.
        /// </summary>
        public static string OrchidPink {
            get {
                return ResourceManager.GetString("OrchidPink", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Pale Dogwood.
        /// </summary>
        public static string PaleDogwood {
            get {
                return ResourceManager.GetString("PaleDogwood", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Pale Pink.
        /// </summary>
        public static string PalePink {
            get {
                return ResourceManager.GetString("PalePink", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Paradise Pink.
        /// </summary>
        public static string ParadisePink {
            get {
                return ResourceManager.GetString("ParadisePink", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Pastel Pink.
        /// </summary>
        public static string PastelPink {
            get {
                return ResourceManager.GetString("PastelPink", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Persian Pink.
        /// </summary>
        public static string PersianPink {
            get {
                return ResourceManager.GetString("PersianPink", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Pick a button in.
        /// </summary>
        public static string PickColorTask {
            get {
                return ResourceManager.GetString("PickColorTask", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Piggy Pink.
        /// </summary>
        public static string PiggyPink {
            get {
                return ResourceManager.GetString("PiggyPink", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Pink.
        /// </summary>
        public static string Pink {
            get {
                return ResourceManager.GetString("Pink", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Pink Lace.
        /// </summary>
        public static string PinkLace {
            get {
                return ResourceManager.GetString("PinkLace", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Pink Lavender.
        /// </summary>
        public static string PinkLavender {
            get {
                return ResourceManager.GetString("PinkLavender", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Pink U.
        /// </summary>
        public static string PinkU {
            get {
                return ResourceManager.GetString("PinkU", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Purple.
        /// </summary>
        public static string Purple {
            get {
                return ResourceManager.GetString("Purple", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Queen Pink.
        /// </summary>
        public static string QueenPink {
            get {
                return ResourceManager.GetString("QueenPink", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Red.
        /// </summary>
        public static string Red {
            get {
                return ResourceManager.GetString("Red", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Reset.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Rose Pink.
        /// </summary>
        public static string RosePink {
            get {
                return ResourceManager.GetString("RosePink", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Rose Pompadour.
        /// </summary>
        public static string RosePompadour {
            get {
                return ResourceManager.GetString("RosePompadour", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Shocking Pink.
        /// </summary>
        public static string ShockingPink {
            get {
                return ResourceManager.GetString("ShockingPink", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Silver Pink.
        /// </summary>
        public static string SilverPink {
            get {
                return ResourceManager.GetString("SilverPink", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Solid Pink.
        /// </summary>
        public static string SolidPink {
            get {
                return ResourceManager.GetString("SolidPink", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Spanish Pink.
        /// </summary>
        public static string SpanishPink {
            get {
                return ResourceManager.GetString("SpanishPink", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu WOW! U did it..
        /// </summary>
        public static string Stage_Cleared {
            get {
                return ResourceManager.GetString("Stage_Cleared", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Start this funy game..
        /// </summary>
        public static string Start_The_Game {
            get {
                return ResourceManager.GetString("Start_The_Game", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Steel Pink.
        /// </summary>
        public static string SteelPink {
            get {
                return ResourceManager.GetString("SteelPink", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Super Pink.
        /// </summary>
        public static string SuperPink {
            get {
                return ResourceManager.GetString("SuperPink", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Tango Pink.
        /// </summary>
        public static string TangoPink {
            get {
                return ResourceManager.GetString("TangoPink", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Tickle Me Pink.
        /// </summary>
        public static string TickleMePink {
            get {
                return ResourceManager.GetString("TickleMePink", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Turquoise.
        /// </summary>
        public static string Turquoise {
            get {
                return ResourceManager.GetString("Turquoise", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Good luck next time..
        /// </summary>
        public static string U_Bad {
            get {
                return ResourceManager.GetString("U_Bad", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Ultra Pink.
        /// </summary>
        public static string UltraPink {
            get {
                return ResourceManager.GetString("UltraPink", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu White.
        /// </summary>
        public static string White {
            get {
                return ResourceManager.GetString("White", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Yellow.
        /// </summary>
        public static string Yellow {
            get {
                return ResourceManager.GetString("Yellow", resourceCulture);
            }
        }
    }
}
