//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NieGadalismyOGrach.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NieGadalismyOGrach.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check.
        /// </summary>
        public static string Check {
            get {
                return ResourceManager.GetString("Check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amaranth Pink.
        /// </summary>
        public static string AmaranthPink {
            get {
                return ResourceManager.GetString("AmaranthPink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baby Pink.
        /// </summary>
        public static string BabyPink {
            get {
                return ResourceManager.GetString("BabyPink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baker-Miller Pink.
        /// </summary>
        public static string BakerMillerPink {
            get {
                return ResourceManager.GetString("BakerMillerPink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barbie Pink.
        /// </summary>
        public static string BarbiePink {
            get {
                return ResourceManager.GetString("BarbiePink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black.
        /// </summary>
        public static string Black {
            get {
                return ResourceManager.GetString("Black", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue.
        /// </summary>
        public static string Blue {
            get {
                return ResourceManager.GetString("Blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bright Pink.
        /// </summary>
        public static string BrightPink {
            get {
                return ResourceManager.GetString("BrightPink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brink Pink.
        /// </summary>
        public static string BrinkPink {
            get {
                return ResourceManager.GetString("BrinkPink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brown.
        /// </summary>
        public static string Brown {
            get {
                return ResourceManager.GetString("Brown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cameo Pink.
        /// </summary>
        public static string CameoPink {
            get {
                return ResourceManager.GetString("CameoPink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carnation Pink.
        /// </summary>
        public static string CarnationPink {
            get {
                return ResourceManager.GetString("CarnationPink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Champagne Pink.
        /// </summary>
        public static string ChampagnePink {
            get {
                return ResourceManager.GetString("ChampagnePink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charm Pink.
        /// </summary>
        public static string CharmPink {
            get {
                return ResourceManager.GetString("CharmPink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cherry Blossom Pink.
        /// </summary>
        public static string CherryBlossomPink {
            get {
                return ResourceManager.GetString("CherryBlossomPink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chilean Pink.
        /// </summary>
        public static string ChileanPink {
            get {
                return ResourceManager.GetString("ChileanPink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to China Pink.
        /// </summary>
        public static string ChinaPink {
            get {
                return ResourceManager.GetString("ChinaPink", resourceCulture);
            }
        }
        
        
        
        /// <summary>
        ///   Looks up a localized string similar to Click the button..
        /// </summary>
        public static string Click_The_Button {
            get {
                return ResourceManager.GetString("Click_The_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations..
        /// </summary>
        public static string Congratz {
            get {
                return ResourceManager.GetString("Congratz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coral Pink.
        /// </summary>
        public static string CoralPink {
            get {
                return ResourceManager.GetString("CoralPink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cotton Candy.
        /// </summary>
        public static string CottonCandy {
            get {
                return ResourceManager.GetString("CottonCandy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click until value is 0.
        /// </summary>
        public static string Count_To_0 {
            get {
                return ResourceManager.GetString("Count_To_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cyan.
        /// </summary>
        public static string Cyan {
            get {
                return ResourceManager.GetString("Cyan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deep Pink.
        /// </summary>
        public static string DeepPink {
            get {
                return ResourceManager.GetString("DeepPink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fairy Tale.
        /// </summary>
        public static string FairyTale {
            get {
                return ResourceManager.GetString("FairyTale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fandango Pink.
        /// </summary>
        public static string FandangoPink {
            get {
                return ResourceManager.GetString("FandangoPink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French Pink.
        /// </summary>
        public static string FrenchPink {
            get {
                return ResourceManager.GetString("FrenchPink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gold.
        /// </summary>
        public static string Gold {
            get {
                return ResourceManager.GetString("Gold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gray.
        /// </summary>
        public static string Gray {
            get {
                return ResourceManager.GetString("Gray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green.
        /// </summary>
        public static string Green {
            get {
                return ResourceManager.GetString("Green", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hot Pink.
        /// </summary>
        public static string HotPink {
            get {
                return ResourceManager.GetString("HotPink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lavender Pink.
        /// </summary>
        public static string LavenderPink {
            get {
                return ResourceManager.GetString("LavenderPink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light Deep Pink.
        /// </summary>
        public static string LightDeepPink {
            get {
                return ResourceManager.GetString("LightDeepPink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light Hot Pink.
        /// </summary>
        public static string LightHotPink {
            get {
                return ResourceManager.GetString("LightHotPink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light Pink.
        /// </summary>
        public static string LightPink {
            get {
                return ResourceManager.GetString("LightPink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lime.
        /// </summary>
        public static string Lime {
            get {
                return ResourceManager.GetString("Lime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mexican Pink.
        /// </summary>
        public static string MexicanPink {
            get {
                return ResourceManager.GetString("MexicanPink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mimi Pink.
        /// </summary>
        public static string MimiPink {
            get {
                return ResourceManager.GetString("MimiPink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mountbatten Pink.
        /// </summary>
        public static string MountbattenPink {
            get {
                return ResourceManager.GetString("MountbattenPink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navy.
        /// </summary>
        public static string Navy {
            get {
                return ResourceManager.GetString("Navy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New York Pink.
        /// </summary>
        public static string NewYorkPink {
            get {
                return ResourceManager.GetString("NewYorkPink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orange.
        /// </summary>
        public static string Orange {
            get {
                return ResourceManager.GetString("Orange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orchid Pink.
        /// </summary>
        public static string OrchidPink {
            get {
                return ResourceManager.GetString("OrchidPink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pale Dogwood.
        /// </summary>
        public static string PaleDogwood {
            get {
                return ResourceManager.GetString("PaleDogwood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pale Pink.
        /// </summary>
        public static string PalePink {
            get {
                return ResourceManager.GetString("PalePink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paradise Pink.
        /// </summary>
        public static string ParadisePink {
            get {
                return ResourceManager.GetString("ParadisePink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pastel Pink.
        /// </summary>
        public static string PastelPink {
            get {
                return ResourceManager.GetString("PastelPink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persian Pink.
        /// </summary>
        public static string PersianPink {
            get {
                return ResourceManager.GetString("PersianPink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick a button in.
        /// </summary>
        public static string PickColorTask {
            get {
                return ResourceManager.GetString("PickColorTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Piggy Pink.
        /// </summary>
        public static string PiggyPink {
            get {
                return ResourceManager.GetString("PiggyPink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pink.
        /// </summary>
        public static string Pink {
            get {
                return ResourceManager.GetString("Pink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pink Lace.
        /// </summary>
        public static string PinkLace {
            get {
                return ResourceManager.GetString("PinkLace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pink Lavender.
        /// </summary>
        public static string PinkLavender {
            get {
                return ResourceManager.GetString("PinkLavender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pink U.
        /// </summary>
        public static string PinkU {
            get {
                return ResourceManager.GetString("PinkU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purple.
        /// </summary>
        public static string Purple {
            get {
                return ResourceManager.GetString("Purple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queen Pink.
        /// </summary>
        public static string QueenPink {
            get {
                return ResourceManager.GetString("QueenPink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red.
        /// </summary>
        public static string Red {
            get {
                return ResourceManager.GetString("Red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rose Pink.
        /// </summary>
        public static string RosePink {
            get {
                return ResourceManager.GetString("RosePink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rose Pompadour.
        /// </summary>
        public static string RosePompadour {
            get {
                return ResourceManager.GetString("RosePompadour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shocking Pink.
        /// </summary>
        public static string ShockingPink {
            get {
                return ResourceManager.GetString("ShockingPink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silver Pink.
        /// </summary>
        public static string SilverPink {
            get {
                return ResourceManager.GetString("SilverPink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solid Pink.
        /// </summary>
        public static string SolidPink {
            get {
                return ResourceManager.GetString("SolidPink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish Pink.
        /// </summary>
        public static string SpanishPink {
            get {
                return ResourceManager.GetString("SpanishPink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WOW! U did it..
        /// </summary>
        public static string Stage_Cleared {
            get {
                return ResourceManager.GetString("Stage_Cleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start this funy game..
        /// </summary>
        public static string Start_The_Game {
            get {
                return ResourceManager.GetString("Start_The_Game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steel Pink.
        /// </summary>
        public static string SteelPink {
            get {
                return ResourceManager.GetString("SteelPink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Super Pink.
        /// </summary>
        public static string SuperPink {
            get {
                return ResourceManager.GetString("SuperPink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tango Pink.
        /// </summary>
        public static string TangoPink {
            get {
                return ResourceManager.GetString("TangoPink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tickle Me Pink.
        /// </summary>
        public static string TickleMePink {
            get {
                return ResourceManager.GetString("TickleMePink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turquoise.
        /// </summary>
        public static string Turquoise {
            get {
                return ResourceManager.GetString("Turquoise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good luck next time..
        /// </summary>
        public static string U_Bad {
            get {
                return ResourceManager.GetString("U_Bad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ultra Pink.
        /// </summary>
        public static string UltraPink {
            get {
                return ResourceManager.GetString("UltraPink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to White.
        /// </summary>
        public static string White {
            get {
                return ResourceManager.GetString("White", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yellow.
        /// </summary>
        public static string Yellow {
            get {
                return ResourceManager.GetString("Yellow", resourceCulture);
            }
        }
    }
}
